export const projectsData = [
  {
    title: "ひきく - Hikiku",
    description:
      "This anime app was built with react and the kitsu api. Discover the highest rated animes based on the showtype, genre, the publication year, or by a search word. Save your favourite animes in a playlist.",
    toolASrc: "Elir-Mahad/porass/main/assets/icons/darkreact.png",
    toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkapi.png",
    toolCSrc: "no",
    websiteUrl: "https://hikiku.netlify.app/",
    repoUrl: "https://github.com/Elir-Mahad/restricted",
    mockSrc: "Elir-Mahad/porass/main/assets/mocks/hikikureactmockup.png",
    tag: "react",
  },
  {
    title: "Radio Interno",
    description:
      "This PWA radio app was built with react, styled components, and the radio-browser-api. You can download it to your device. Discover radio stations based on your favourite music genre, language or country. Listen, enjoy, and then save your favourite stations in a playlist.",
    toolASrc: "Elir-Mahad/porass/main/assets/icons/darkreact.png",
    toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkapi.png",
    toolCSrc: "no",
    websiteUrl: "https://interno.netlify.app/",
    repoUrl: "https://github.com/Elir-Mahad/restricted",
    mockSrc: "Elir-Mahad/porass/main/assets/mocks/internomockup.png",
    tag: "react",
  },
  // {
  //   title: "Blog",
  //   description:
  //     "This is my blog. It was built with next.js and styled components. I write about github, git, react, python, data science and other topics.",
  //   toolASrc: "Elir-Mahad/porass/main/assets/icons/next.png",
  //   toolBSrc: "no",
  //   toolCSrc: "no",
  //   websiteUrl: "no",
  //   repoUrl: "no",
  //   mockSrc: "Elir-Mahad/porass/main/assets/mocks/blogmockup.png",
  //   tag: "react",
  // },
  {
    title: "Jokery",
    description:
      "  This joke app was built with react, styled components, and a jokes api. You can download it to your device. Read one part or two part jokes, based on different categories. Laugh your heart out.",
    toolASrc: "Elir-Mahad/porass/main/assets/icons/darkreact.png",
    toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkapi.png",
    toolCSrc: "no",
    websiteUrl: "https://jokery.netlify.app/",
    repoUrl: "https://github.com/Elir-Mahad/jokery",
    mockSrc: "Elir-Mahad/porass/main/assets/mocks/jokerymockup.png",
    tag: "react",
  },
  {
    title: "Searchsquid",
    description:
      "This search engine app was built with react and google’s programmable search engine api. Enter a search word, and browse the results.",
    toolASrc: "Elir-Mahad/porass/main/assets/icons/darkreact.png",
    toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkapi.png",
    toolCSrc: "no",
    websiteUrl: "https://elir-mahad.github.io/searchsquid/",
    repoUrl: "https://github.com/Elir-Mahad/restricted",
    mockSrc: "Elir-Mahad/porass/main/assets/mocks/searchsquidmockup.png",
    tag: "react",
  },
  // {
  //   title: "Flicks",
  //   description:
  //     "This movie app was built with react and the TMDB (the movie database) api. Discover the latest movies and tv shows based on the genre.",
  //   toolASrc: "Elir-Mahad/porass/main/assets/icons/darkreact.png",
  //   toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkapi.png",
  //   toolCSrc: "no",
  //   websiteUrl: "https://elir-mahad.github.io/flicks/",
  //   repoUrl: "https://github.com/Elir-Mahad/restricted",
  //   mockSrc: "Elir-Mahad/porass/main/assets/mocks/flicksmockup.png",
  //   tag: "react",
  // },
  // {
  //   title: "Hikiku_v1",
  //   description:
  //     "This anime app was built with jquery and the kitsu api. Discover the most popular anime movies and shows based on the genre.",
  //   toolASrc: "Elir-Mahad/porass/main/assets/icons/darkjquery.png",
  //   toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkapi.png",
  //   toolCSrc: "no",
  //   websiteUrl: "https://elir-mahad.github.io/hikiku/",
  //   repoUrl: "https://github.com/Elir-Mahad/hikiku",
  //   mockSrc: "Elir-Mahad/porass/main/assets/mocks/hikikumockup.png",
  //   tag: "jquery",
  // },
  {
    title: "Huawei clone",
    description:
      "Clone of the huawei website made using flexbox and best accessibility practices. Responsive across devices.",
    toolASrc: "Elir-Mahad/porass/main/assets/icons/darkhtml2.png",
    toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkcss.png",
    toolCSrc: "no",
    websiteUrl: "https://hwa-clone.netlify.app",
    repoUrl: "https://github.com/Elir-Mahad/restricted",
    mockSrc: "Elir-Mahad/porass/main/assets/mocks/huaweimockup.png",
    tag: "html",
  },
  {
    title: "Jumia clone",
    description:
      "Multi-page site made using flexbox, and best accessibility practices. Responsive across devices.",
    toolASrc: "Elir-Mahad/porass/main/assets/icons/darkhtml2.png",
    toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkcss.png",
    toolCSrc: "no",
    websiteUrl: "https://jum-clone.netlify.app",
    repoUrl: "https://github.com/Elir-Mahad/restricted",
    mockSrc: "Elir-Mahad/porass/main/assets/mocks/jumiamockup.png",
    tag: "html",
  },
  // {
  //   title: "Creative clone",
  //   description:
  //     " Multi-page site made using flexbox, and best accessibility practices. Responsive across devices.",
  //   toolASrc: "Elir-Mahad/porass/main/assets/icons/darkhtml2.png",
  //   toolBSrc: "Elir-Mahad/porass/main/assets/icons/darkcss.png",
  //   toolCSrc: "no",
  //   websiteUrl: "https://elir-mahad.github.io/creativeclone",
  //   repoUrl: "https://github.com/Elir-Mahad/restricted",
  //   mockSrc: "Elir-Mahad/porass/main/assets/mocks/creativeclonemockup.png",
  //   tag: "html",
  // },
];
